// <auto-generated />
using M4_Project_v2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace M4_Project_v2.Migrations
{
    [DbContext(typeof(ContactContext))]
    [Migration("20240207012613_Inital")]
    partial class Inital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("M4_Project_v2.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Friend",
                            Email = "delores@hotmail.com",
                            Fname = "Delores",
                            Lname = "Del Rio",
                            Phone = "555-987-6543"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Work",
                            Email = "efren@aol.com",
                            Fname = "Efren",
                            Lname = "Herrera",
                            Phone = "555-456-7890"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Family",
                            Email = "MaryEllen@yahoo.com",
                            Fname = "Mary Ellen",
                            Lname = "Walton",
                            Phone = "555-123-4567"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
